[package]
name = "find-id-ui"
version = "0.2.0"
edition = "2024"

[dependencies]
rfd = "0.15.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
slint = "1.13.0"
glob = "0.3.2"
rayon = "1.10.0"
roxmltree = "0.20.0"


[build-dependencies]
slint-build = "1.13.0"
